<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Employee Attendance</title><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>body{font-family:Inter,sans-serif}main input,main select{border-color:#cbd5e1;outline:none}main input:focus,main select:focus{border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.1)}</style></head>
<body class="bg-slate-50"><?php
$formatMinutes=static function(int $minutes):string{return sprintf('%dh %02dm',intdiv(max(0,$minutes),60),max(0,$minutes)%60);};
$workedMinutes=static function(array $row):int{if(empty($row['check_in']))return 0;$end=!empty($row['check_out'])?strtotime($row['check_out']):time();$active=!empty($row['break_started_at'])?max(0,(int)floor(($end-strtotime($row['break_started_at']))/60)):0;return max(0,(int)floor(($end-strtotime($row['check_in']))/60)-(int)$row['break_minutes']-$active);};
$todayMinutes=$today?$workedMinutes($today):0;$query=http_build_query(['from'=>$from,'to'=>$to,'status'=>$statusFilter]);
?><div id="sidebarOverlay" class="fixed inset-0 z-40 hidden bg-black/40 lg:hidden"></div><div class="flex h-screen overflow-hidden"><?php include __DIR__.'/sidebar.php'; ?><div class="flex min-w-0 flex-1 flex-col overflow-hidden"><?php include __DIR__.'/navbar.php'; ?><main class="flex-1 overflow-y-auto p-4 lg:p-6">
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="mb-2 text-xs font-bold uppercase tracking-[.18em] text-blue-600">Workforce</p><h1 class="text-2xl font-extrabold tracking-tight text-slate-950 sm:text-3xl">Employee Attendance</h1><p class="mt-1 text-sm text-slate-500">Your live attendance record and monthly totals</p></div><a href="<?= base_url('employee_attendance/export?'.$query) ?>" class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm hover:border-blue-200 hover:text-blue-700"><i data-lucide="download" class="h-4 w-4"></i>Export CSV</a></div>
<div class="grid gap-5 xl:grid-cols-[320px_1fr]"><section class="rounded-xl border bg-white p-5 text-center shadow-sm"><p class="text-sm font-semibold text-slate-500">Hello, <?= esc(session('name') ?: 'Employee') ?></p><div id="liveClock" class="mt-2 text-xl font-bold text-slate-900"></div><div class="mx-auto mt-6 flex h-28 w-28 items-center justify-center rounded-full border-4 <?= $today&&!$today['check_out']?'border-emerald-500 bg-emerald-50':'border-slate-200 bg-slate-50' ?>"><i data-lucide="fingerprint" class="h-12 w-12 <?= $today&&!$today['check_out']?'text-emerald-600':'text-slate-400' ?>"></i></div>
<?php if(!$today): ?><p class="mt-5 text-sm text-slate-500">You have not punched in today.</p><form method="post" action="<?= base_url('employee_attendance/punch') ?>" class="mt-4"><?= csrf_field() ?><button class="w-full rounded-lg bg-slate-900 py-3 text-sm font-semibold text-white">Punch In</button></form>
<?php elseif(!$today['check_out']): ?><p class="mt-5 text-sm font-semibold text-slate-800">Punched in at <?= date('h:i A',strtotime($today['check_in'])) ?></p><p class="mt-1 text-sm text-emerald-600"><?= $formatMinutes($todayMinutes) ?> worked</p><div class="mt-4 grid grid-cols-2 gap-2"><form method="post" action="<?= base_url('employee_attendance/break') ?>"><?= csrf_field() ?><button class="w-full rounded-lg border border-amber-500 py-3 text-sm font-semibold text-amber-700"><?= $today['break_started_at']?'End Break':'Start Break' ?></button></form><form method="post" action="<?= base_url('employee_attendance/punch') ?>"><?= csrf_field() ?><button class="w-full rounded-lg bg-slate-900 py-3 text-sm font-semibold text-white">Punch Out</button></form></div>
<?php else: ?><p class="mt-5 text-sm font-semibold text-slate-800">Shift completed</p><p class="mt-1 text-sm text-slate-500"><?= date('h:i A',strtotime($today['check_in'])) ?> – <?= date('h:i A',strtotime($today['check_out'])) ?></p><p class="mt-2 font-semibold text-emerald-600"><?= $formatMinutes($todayMinutes) ?> worked</p><?php endif; ?></section>
<div><div class="grid grid-cols-2 gap-4 lg:grid-cols-4"><?php $cards=[['Worked this month',$formatMinutes($summary['minutes']),'clock-3','orange'],['Overtime',$formatMinutes($summary['overtime']),'timer','blue'],['Days present',$summary['present'],'calendar-check','emerald'],['Late arrivals',$summary['late'],'alarm-clock','rose']];foreach($cards as [$label,$value,$icon,$color]): ?><div class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex h-9 w-9 items-center justify-center rounded-lg bg-<?= $color ?>-100 text-<?= $color ?>-600"><i data-lucide="<?= $icon ?>" class="h-5 w-5"></i></div><div class="mt-4 text-2xl font-bold text-slate-900"><?= esc($value) ?></div><div class="mt-1 text-sm text-slate-500"><?= esc($label) ?></div></div><?php endforeach; ?></div>
<section class="mt-5 overflow-hidden rounded-xl border bg-white shadow-sm"><form method="get" class="flex flex-wrap items-end gap-3 border-b p-4"><label class="text-xs font-semibold text-slate-600">From<input type="date" name="from" value="<?= esc($from) ?>" class="mt-1 block rounded-lg border px-3 py-2 text-sm"></label><label class="text-xs font-semibold text-slate-600">To<input type="date" name="to" value="<?= esc($to) ?>" class="mt-1 block rounded-lg border px-3 py-2 text-sm"></label><label class="text-xs font-semibold text-slate-600">Status<select name="status" class="mt-1 block rounded-lg border px-3 py-2 text-sm"><option value="">All</option><option value="Present" <?= $statusFilter==='Present'?'selected':'' ?>>Present</option><option value="Late" <?= $statusFilter==='Late'?'selected':'' ?>>Late</option></select></label><label class="text-xs font-semibold text-slate-600">Rows<select name="per_page" class="mt-1 block rounded-lg border px-3 py-2 text-sm"><?php foreach([5,10,25,50] as $size): ?><option <?= $perPage===$size?'selected':'' ?>><?= $size ?></option><?php endforeach; ?></select></label><button class="rounded-lg bg-orange-500 px-5 py-2 text-sm font-semibold text-white">Apply</button><a href="<?= base_url('employee_attendance') ?>" class="px-2 py-2 text-sm font-semibold text-slate-500">Reset</a></form>
<div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Check in</th><th class="px-5 py-3">Check out</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Break</th><th class="px-5 py-3">Worked</th><th class="px-5 py-3">Overtime</th></tr></thead><tbody class="divide-y"><?php foreach($records as $row): $minutes=$workedMinutes($row); ?><tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-slate-800"><?= date('d M Y',strtotime($row['attendance_date'])) ?></td><td class="px-5 py-4"><?= date('h:i A',strtotime($row['check_in'])) ?></td><td class="px-5 py-4"><?= $row['check_out']?date('h:i A',strtotime($row['check_out'])):'Open shift' ?></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-semibold <?= $row['status']==='Late'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700' ?>"><?= esc($row['status']) ?></span></td><td class="px-5 py-4"><?= (int)$row['break_minutes'] ?> min<?= $row['break_started_at']?' (active)':'' ?></td><td class="px-5 py-4 font-semibold"><?= $formatMinutes($minutes) ?></td><td class="px-5 py-4"><?= $formatMinutes(max(0,$minutes-480)) ?></td></tr><?php endforeach; ?><?php if(!$records): ?><tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">No attendance records match these filters.</td></tr><?php endif; ?></tbody></table></div><div class="border-t px-5 py-4"><?= $pager->links() ?></div></section></div></div>
</main></div></div><?= view('partials/flash_toast',['toastSuccess'=>session()->getFlashdata('success'),'toastError'=>session()->getFlashdata('error')]) ?><script>lucide.createIcons();function tick(){document.getElementById('liveClock').textContent=new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'medium'}).format(new Date())}tick();setInterval(tick,1000);</script></body></html>
