<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offer Letter</title>
<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;color:#1e293b;margin:0;background:#f8fafc}.page{max-width:780px;margin:32px auto;background:#fff;padding:64px;border:1px solid #e2e8f0;border-radius:20px;box-shadow:0 18px 50px rgba(15,23,42,.08);position:relative}.page:before{content:"";display:block;width:56px;height:6px;margin-bottom:26px;border-radius:99px;background:#2563eb}h1{font-size:30px;letter-spacing:-.03em;margin:0;color:#0f172a}.muted{color:#64748b}.terms{margin:30px 0;border-collapse:separate;border-spacing:0;width:100%;overflow:hidden;border:1px solid #e2e8f0;border-radius:12px}.terms td{padding:13px 15px;border-bottom:1px solid #e2e8f0}.terms tr:last-child td{border-bottom:0}.terms td:first-child{width:38%;background:#f8fafc;color:#64748b;font-size:13px;font-weight:600}.signature{margin-top:50px;border-top:1px solid #e2e8f0;padding-top:20px}.print{position:fixed;right:24px;top:24px;padding:11px 18px;background:#2563eb;color:#fff;border:0;border-radius:12px;font:700 13px Inter,Arial;box-shadow:0 8px 20px rgba(37,99,235,.2);cursor:pointer}@media(max-width:820px){.page{margin:0;border:0;border-radius:0;padding:36px 24px}.print{position:static;margin:16px}}@media print{body{background:#fff}.page{box-shadow:none;margin:0;max-width:none;border:0;border-radius:0}.print{display:none}}</style></head>
<body><button class="print" onclick="window.print()">Print / Save PDF</button><article class="page">
<p class="muted"><?= esc($companyName) ?></p><h1>Employment Offer Letter</h1><p class="muted">Issued <?= esc(date('d F Y', strtotime($application['offer_sent_at'] ?: 'now'))) ?></p>
<p>Dear <?= esc($application['candidate_name'] ?: $application['name']) ?>,</p><p>We are pleased to offer you employment with <?= esc($companyName) ?>. Your experience and performance during the selection process make you a strong addition to our team.</p>
<table class="terms"><tr><td>Position</td><td><strong><?= esc($application['job_title']) ?></strong></td></tr><tr><td>Department</td><td><?= esc($application['department']) ?></td></tr><tr><td>Employment type</td><td><?= esc($application['employment_type']) ?></td></tr><tr><td>Work location</td><td><?= esc($application['location'] ?: 'As assigned') ?></td></tr><tr><td>Annual compensation</td><td><?= number_format((float)$application['offered_salary'], 2) ?></td></tr><tr><td>Proposed joining date</td><td><?= esc(date('d F Y', strtotime($application['proposed_joining_date']))) ?></td></tr></table>
<?php if ($application['salary_notes']): ?><p><strong>Additional terms</strong><br><?= nl2br(esc($application['salary_notes'])) ?></p><?php endif; ?><p>This offer remains subject to the verified documents and company employment policies. Please accept through your candidate portal.</p>
<div class="signature"><p>For <?= esc($companyName) ?></p><?php if ($application['signature_name']): ?><p style="margin-top:40px"><strong>Electronically accepted by <?= esc($application['signature_name']) ?></strong><br><span class="muted"><?= esc(date('d F Y, h:i A', strtotime($application['offer_responded_at']))) ?></span></p><?php endif; ?></div>
</article></body></html>
