<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offer Letter</title>
<style>body{font-family:Arial,sans-serif;color:#1e293b;margin:0;background:#f1f5f9}.page{max-width:760px;margin:30px auto;background:#fff;padding:64px;box-shadow:0 2px 12px #cbd5e1}h1{font-size:28px;margin:0}.muted{color:#64748b}.terms{margin:30px 0;border-collapse:collapse;width:100%}.terms td{padding:12px;border:1px solid #cbd5e1}.signature{margin-top:50px;border-top:1px solid #cbd5e1;padding-top:20px}.print{position:fixed;right:24px;top:24px;padding:10px 18px;background:#0f172a;color:#fff;border:0;border-radius:6px}@media print{body{background:#fff}.page{box-shadow:none;margin:0;max-width:none}.print{display:none}}</style></head>
<body><button class="print" onclick="window.print()">Print / Save PDF</button><article class="page">
<p class="muted"><?= esc($companyName) ?></p><h1>Employment Offer Letter</h1><p class="muted">Issued <?= esc(date('d F Y', strtotime($application['offer_sent_at'] ?: 'now'))) ?></p>
<p>Dear <?= esc($application['candidate_name'] ?: $application['name']) ?>,</p><p>We are pleased to offer you employment with <?= esc($companyName) ?>. Your experience and performance during the selection process make you a strong addition to our team.</p>
<table class="terms"><tr><td>Position</td><td><strong><?= esc($application['job_title']) ?></strong></td></tr><tr><td>Department</td><td><?= esc($application['department']) ?></td></tr><tr><td>Employment type</td><td><?= esc($application['employment_type']) ?></td></tr><tr><td>Work location</td><td><?= esc($application['location'] ?: 'As assigned') ?></td></tr><tr><td>Annual compensation</td><td><?= number_format((float)$application['offered_salary'], 2) ?></td></tr><tr><td>Proposed joining date</td><td><?= esc(date('d F Y', strtotime($application['proposed_joining_date']))) ?></td></tr></table>
<?php if ($application['salary_notes']): ?><p><strong>Additional terms</strong><br><?= nl2br(esc($application['salary_notes'])) ?></p><?php endif; ?><p>This offer remains subject to the verified documents and company employment policies. Please accept through your candidate portal.</p>
<div class="signature"><p>For <?= esc($companyName) ?></p><?php if ($application['signature_name']): ?><p style="margin-top:40px"><strong>Electronically accepted by <?= esc($application['signature_name']) ?></strong><br><span class="muted"><?= esc(date('d F Y, h:i A', strtotime($application['offer_responded_at']))) ?></span></p><?php endif; ?></div>
</article></body></html>
