<?php
$applications = $applications ?? [];
$offerCount = count($applications);
$verifiedCount = count(array_filter($applications, static fn($row) => ($row['verification_status'] ?? '') === 'Verified'));
$acceptedCount = count(array_filter($applications, static fn($row) => in_array(($row['offer_status'] ?? ''), ['Accepted', 'Hired'], true)));
$hiredCount = count(array_filter($applications, static fn($row) => ($row['offer_status'] ?? '') === 'Hired' || ($row['application_status'] ?? '') === 'Hired'));
$statusClass = static function (string $status): string { return match ($status) { 'Verified', 'Accepted', 'Hired' => 'border-emerald-200 bg-emerald-50 text-emerald-700', 'Failed', 'Declined', 'Rejected' => 'border-rose-200 bg-rose-50 text-rose-700', 'Sent', 'Documents Requested', 'Documents Submitted' => 'border-blue-200 bg-blue-50 text-blue-700', default => 'border-slate-200 bg-slate-50 text-slate-600' }; };
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offers & Onboarding | GICHRMS</title><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><style>body{font-family:Inter,system-ui,sans-serif}</style></head>
<body class="bg-slate-50"><div id="sidebarOverlay" class="fixed inset-0 z-40 hidden bg-black/40 lg:hidden"></div><div class="flex h-screen overflow-hidden"><?php include __DIR__ . '/../sidebar.php'; ?><div class="flex min-w-0 flex-1 flex-col overflow-hidden"><?php include __DIR__ . '/../navbar.php'; ?>
<main class="flex-1 overflow-y-auto p-4 lg:p-6"><div class="mx-auto max-w-[1180px]">
    <div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-blue-600">Recruitment</p><h1 class="mt-2 text-3xl font-black tracking-tight text-slate-950">Offers & Onboarding</h1><p class="mt-2 text-sm text-slate-500">Manage compensation, verification, offer acceptance, and employee conversion.</p></div>
    <div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><?php foreach ([['files',$offerCount,'Candidates','blue'],['badge-check',$verifiedCount,'Verified','emerald'],['file-signature',$acceptedCount,'Accepted','violet'],['user-check',$hiredCount,'Hired','amber']] as [$icon,$count,$label,$tone]): ?><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-slate-500"><?= esc($label) ?></span><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-<?= $tone ?>-50 text-<?= $tone ?>-600"><i data-lucide="<?= $icon ?>" class="h-4 w-4"></i></span></div><p class="mt-3 text-3xl font-black text-slate-950"><?= $count ?></p></div><?php endforeach; ?></div>
    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-5"><h2 class="text-[15px] font-extrabold text-slate-950">Offer Pipeline</h2><p class="mt-1 text-xs text-slate-500">Selected candidates ready for offer and onboarding activities.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[860px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Candidate</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Verification</th><th class="px-5 py-3">Offer stage</th><th class="px-5 py-3 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
    <?php foreach ($applications as $row): ?><?php $name=$row['candidate_name'] ?: $row['name']; $verification=$row['verification_status'] ?: 'Not started'; $offer=$row['offer_status'] ?: $row['application_status']; ?><tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 font-bold text-blue-600"><?= esc(substr($name,0,1)) ?></span><div><div class="font-bold text-slate-900"><?= esc($name) ?></div><div class="mt-1 text-xs text-slate-500"><?= esc($row['candidate_email'] ?: $row['email']) ?></div></div></div></td><td class="px-5 py-4"><p class="font-semibold text-slate-800"><?= esc($row['job_title']) ?></p><p class="mt-1 text-xs text-slate-500"><?= esc($row['department'] ?? '-') ?></p></td><td class="px-5 py-4"><span class="inline-flex rounded-full border px-3 py-1 text-xs font-bold <?= $statusClass($verification) ?>"><?= esc($verification) ?></span></td><td class="px-5 py-4"><span class="inline-flex rounded-full border px-3 py-1 text-xs font-bold <?= $statusClass($offer) ?>"><?= esc($offer) ?></span></td><td class="px-5 py-4 text-right"><a class="inline-flex h-9 items-center gap-2 rounded-lg bg-blue-600 px-3 text-xs font-bold text-white hover:bg-blue-700" href="<?= base_url('Recruitment/offers/' . $row['application_id']) ?>">Open workflow <i data-lucide="arrow-right" class="h-3.5 w-3.5"></i></a></td></tr><?php endforeach; ?>
    <?php if (!$applications): ?><tr><td colspan="5" class="px-5 py-14 text-center text-slate-500"><i data-lucide="inbox" class="mx-auto h-7 w-7 text-slate-400"></i><p class="mt-3 text-sm">No selected candidates are ready for this stage.</p></td></tr><?php endif; ?></tbody></table></div></section>
</div></main></div></div><?= view('partials/flash_toast', ['toastSuccess'=>session()->getFlashdata('success'),'toastError'=>session()->getFlashdata('error')]) ?><script>lucide.createIcons();function toggleSidebar(){document.getElementById('sidebar').classList.toggle('-translate-x-full');document.getElementById('sidebarOverlay').classList.toggle('hidden')}document.getElementById('sidebarOverlay').addEventListener('click',function(){document.getElementById('sidebar').classList.add('-translate-x-full');this.classList.add('hidden')})</script></body></html>
