<?php
$id = $application['application_id'];
$status = $application['application_status'];
$candidateName = $application['candidate_name'] ?: $application['name'];
$offerStatus = $application['offer_status'] ?? '';
$fieldClass = 'w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-100';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offer Workflow | GICHRMS</title><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><style>body{font-family:Inter,system-ui,sans-serif}</style></head>
<body class="bg-slate-50"><div id="sidebarOverlay" class="fixed inset-0 z-40 hidden bg-black/40 lg:hidden"></div><div class="flex h-screen overflow-hidden"><?php include __DIR__ . '/../sidebar.php'; ?><div class="flex min-w-0 flex-1 flex-col overflow-hidden"><?php include __DIR__ . '/../navbar.php'; ?><main class="flex-1 overflow-y-auto p-4 lg:p-6"><div class="mx-auto max-w-[1180px]">
    <a href="<?= base_url('Recruitment/offers') ?>" class="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-blue-700"><i data-lucide="arrow-left" class="h-4 w-4"></i> Offers & Onboarding</a>
    <div class="mt-5 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-blue-600">Candidate workflow</p><div class="mt-2 flex items-center gap-3"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-lg font-black text-blue-600"><?= esc(substr($candidateName,0,1)) ?></span><div><h1 class="text-2xl font-black tracking-tight text-slate-950 sm:text-3xl"><?= esc($candidateName) ?></h1><p class="mt-1 text-sm text-slate-500"><?= esc($application['job_title']) ?> · <?= esc($application['department']) ?></p></div></div></div><span class="self-start rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><?= esc($status) ?></span></div>

    <div class="mt-6 grid gap-5 xl:grid-cols-2">
        <?php if ($canManage): ?><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center gap-3 border-b border-slate-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 font-black text-blue-600">1</span><div><h2 class="text-[15px] font-extrabold">Salary package & document request</h2><p class="mt-0.5 text-xs text-slate-500">Set compensation and begin document collection.</p></div></div><form method="post" action="<?= base_url("Recruitment/offers/$id/request-documents") ?>" class="space-y-3 p-5"><?= csrf_field() ?><label class="block text-sm font-bold text-slate-700">Annual salary<input required type="number" min="1" step="0.01" name="offered_salary" value="<?= esc($application['offered_salary'] ?? '') ?>" placeholder="Annual salary" class="mt-2 <?= $fieldClass ?>"></label><label class="block text-sm font-bold text-slate-700">Proposed joining date<input required type="date" name="proposed_joining_date" value="<?= esc($application['proposed_joining_date'] ?? '') ?>" class="mt-2 <?= $fieldClass ?>"></label><label class="block text-sm font-bold text-slate-700">Package notes<textarea name="salary_notes" rows="3" placeholder="Package notes" class="mt-2 <?= $fieldClass ?>"><?= esc($application['salary_notes'] ?? '') ?></textarea></label><button class="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white hover:bg-blue-700"><i data-lucide="send" class="h-4 w-4"></i> Save & request documents</button></form></section><?php endif; ?>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center gap-3 border-b border-slate-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 font-black text-blue-600">2</span><div><h2 class="text-[15px] font-extrabold">Candidate documents</h2><p class="mt-0.5 text-xs text-slate-500">Verification status: <b><?= esc($application['verification_status'] ?: 'Not requested') ?></b></p></div></div><div class="p-5">
            <?php if (!$canManage && in_array($status,['Documents Requested','Documents Submitted'],true)): ?><form enctype="multipart/form-data" method="post" action="<?= base_url("Recruitment/offers/$id/upload-documents") ?>" class="space-y-3"><?= csrf_field() ?><label class="block text-sm font-bold text-slate-700">BGV / identity document<input type="file" name="bgv" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-xl border border-slate-300 p-2 text-sm"></label><label class="block text-sm font-bold text-slate-700">Experience document<input type="file" name="experience" accept=".pdf,.jpg,.jpeg,.png" class="mt-2 block w-full rounded-xl border border-slate-300 p-2 text-sm"></label><button class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Submit documents</button></form><?php endif; ?>
            <div class="flex flex-wrap gap-3 text-sm"><?php if($application['bgv_document']): ?><a class="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 font-bold text-blue-700" href="<?= base_url("Recruitment/offers/$id/document/bgv") ?>"><i data-lucide="file-text" class="h-4 w-4"></i> BGV document</a><?php endif; ?><?php if($application['experience_document']): ?><a class="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 font-bold text-blue-700" href="<?= base_url("Recruitment/offers/$id/document/experience") ?>"><i data-lucide="file-check" class="h-4 w-4"></i> Experience document</a><?php endif; ?><?php if(!$application['bgv_document'] && !$application['experience_document']): ?><p class="text-sm text-slate-500">No documents uploaded yet.</p><?php endif; ?></div>
        </div></section>

        <?php if ($canManage): ?><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center gap-3 border-b border-slate-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 font-black text-blue-600">3</span><div><h2 class="text-[15px] font-extrabold">Verification</h2><p class="mt-0.5 text-xs text-slate-500">Record document verification results.</p></div></div><form method="post" action="<?= base_url("Recruitment/offers/$id/verify") ?>" class="space-y-3 p-5"><?= csrf_field() ?><select name="verification_status" class="<?= $fieldClass ?>"><option>Verified</option><option>Failed</option></select><textarea name="verification_notes" rows="3" placeholder="Verification notes" class="<?= $fieldClass ?>"><?= esc($application['verification_notes'] ?? '') ?></textarea><button class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-700">Save verification</button></form></section>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center gap-3 border-b border-slate-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 font-black text-blue-600">4</span><div><h2 class="text-[15px] font-extrabold">Issue offer</h2><p class="mt-0.5 text-xs text-slate-500">Review the package and issue the formal letter.</p></div></div><div class="p-5"><div class="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm"><div><p class="text-xs text-slate-500">Annual salary</p><b class="mt-1 block"><?= $application['offered_salary'] ? number_format((float)$application['offered_salary'],2) : '-' ?></b></div><div><p class="text-xs text-slate-500">Joining date</p><b class="mt-1 block"><?= esc($application['proposed_joining_date'] ?: '-') ?></b></div></div><?php if(in_array($offerStatus, ['Sent','Accepted','Hired'],true)): ?><a target="_blank" href="<?= base_url("Recruitment/offers/$id/letter") ?>" class="mt-4 inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm font-bold text-blue-700"><i data-lucide="file-signature" class="h-4 w-4"></i> View / print offer letter</a><?php else: ?><form method="post" action="<?= base_url("Recruitment/offers/$id/send") ?>" class="mt-4"><?= csrf_field() ?><button class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Digitally issue offer letter</button></form><?php endif; ?></div></section><?php endif; ?>

        <?php if (!$canManage && in_array($offerStatus, ['Sent','Accepted','Hired'],true)): ?><div class="xl:col-span-2"><a target="_blank" href="<?= base_url("Recruitment/offers/$id/letter") ?>" class="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-sm font-bold text-blue-700"><i data-lucide="file-signature" class="h-4 w-4"></i> View / print complete offer letter</a></div><?php endif; ?>

        <?php if (!$canManage && $offerStatus==='Sent'): ?><section class="overflow-hidden rounded-2xl border-2 border-emerald-300 bg-white shadow-sm xl:col-span-2"><div class="flex items-center gap-3 border-b border-emerald-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 font-black text-emerald-600">5</span><h2 class="text-[15px] font-extrabold">Review and digitally sign</h2></div><div class="p-5"><p class="text-sm leading-6 text-slate-600">I accept the offer for <b><?= esc($application['job_title']) ?></b>, with proposed joining date <b><?= esc($application['proposed_joining_date']) ?></b> and annual salary <b><?= number_format((float)$application['offered_salary'],2) ?></b>.</p><form method="post" action="<?= base_url("Recruitment/offers/$id/respond") ?>" class="mt-4 space-y-3"><?= csrf_field() ?><input name="signature_name" placeholder="Type your full legal name" class="<?= $fieldClass ?>"><label class="flex gap-2 text-sm"><input type="checkbox" name="consent" value="1"> I agree that this typed name is my electronic signature.</label><textarea name="offer_decline_reason" placeholder="Reason if declining" class="<?= $fieldClass ?>"></textarea><div class="flex flex-wrap gap-3"><button name="decision" value="accept" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">Accept & sign</button><button name="decision" value="decline" class="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white">Decline offer</button></div></form></div></section><?php endif; ?>

        <?php if ($canManage && $offerStatus==='Accepted'): ?><section class="overflow-hidden rounded-2xl border-2 border-emerald-300 bg-white shadow-sm xl:col-span-2"><div class="flex items-center gap-3 border-b border-emerald-100 p-5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-50 font-black text-emerald-600">6</span><div><h2 class="text-[15px] font-extrabold">Hire & pre-onboard</h2><p class="mt-0.5 text-xs text-slate-500">Signed by <?= esc($application['signature_name']) ?></p></div></div><form method="post" action="<?= base_url("Recruitment/offers/$id/hire") ?>" class="space-y-3 p-5"><?= csrf_field() ?><textarea name="onboarding_notes" rows="3" class="<?= $fieldClass ?>" placeholder="Pre-onboarding instructions or notes"></textarea><button class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800">Mark hired & convert to employee</button></form></section><?php endif; ?>
    </div>
</div></main></div></div><?= view('partials/flash_toast',['toastSuccess'=>session()->getFlashdata('success'),'toastError'=>session()->getFlashdata('error')]) ?><script>lucide.createIcons();function toggleSidebar(){document.getElementById('sidebar').classList.toggle('-translate-x-full');document.getElementById('sidebarOverlay').classList.toggle('hidden')}document.getElementById('sidebarOverlay').addEventListener('click',function(){document.getElementById('sidebar').classList.add('-translate-x-full');this.classList.add('hidden')})</script></body></html>
