<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Careers | GICHRMS</title><script src="https://cdn.tailwindcss.com"></script><script src="https://unpkg.com/lucide@latest"></script></head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<header class="border-b border-slate-200 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="<?= base_url('careers') ?>" class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600 text-white"><i data-lucide="building-2" class="h-5 w-5"></i></span><span><b class="block">GICHRMS Careers</b><span class="text-xs text-slate-500">Build your future with us</span></span></a><a href="<?= base_url('login') ?>" class="text-sm font-semibold text-indigo-700">Employee sign in</a></div></header>
<main>
<section class="bg-slate-950 px-5 py-16 text-white lg:px-8"><div class="mx-auto max-w-7xl"><p class="text-sm font-bold uppercase tracking-[.2em] text-indigo-300">Open opportunities</p><h1 class="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">Do meaningful work with a team that values your growth.</h1><p class="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Explore current openings across our companies and apply directly—no employee account required.</p></div></section>
<section class="mx-auto max-w-7xl px-5 py-10 lg:px-8">
<?php if ($message = session()->getFlashdata('error')): ?><div class="mb-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><?= esc($message) ?></div><?php endif; ?>
<form method="get" action="<?= base_url('careers') ?>" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-5">
<label class="md:col-span-2"><span class="sr-only">Search roles</span><input name="search" value="<?= esc($filters['search'], 'attr') ?>" placeholder="Search title, skills, or keywords" class="h-11 w-full rounded-xl border border-slate-300 px-4 text-sm outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100"></label>
<?php foreach ([['department','Department',$departments],['location','Location',$locations],['type','Job type',$types]] as [$name,$label,$options]): ?><label><span class="sr-only"><?= esc($label) ?></span><select name="<?= esc($name) ?>" class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"><option value=""><?= esc($label) ?></option><?php foreach ($options as $option): ?><option value="<?= esc($option, 'attr') ?>" <?= $filters[$name] === $option ? 'selected' : '' ?>><?= esc($option) ?></option><?php endforeach; ?></select></label><?php endforeach; ?>
<div class="flex gap-2 md:col-span-5"><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white">Search jobs</button><a href="<?= base_url('careers') ?>" class="rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-600">Clear</a></div>
</form>
<div class="mt-8 flex items-end justify-between"><div><h2 class="text-2xl font-bold">Current openings</h2><p class="mt-1 text-sm text-slate-500"><?= count($jobs) ?> role<?= count($jobs) === 1 ? '' : 's' ?> available</p></div></div>
<div class="mt-5 grid gap-4 lg:grid-cols-2">
<?php foreach ($jobs as $job): ?><article class="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-lg"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-indigo-600"><?= esc($job['company_name']) ?></p><h3 class="mt-2 text-xl font-bold group-hover:text-indigo-700"><?= esc($job['job_title']) ?></h3></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700"><?= esc($job['employment_type']) ?></span></div><div class="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500"><span class="flex items-center gap-1.5"><i data-lucide="building" class="h-4 w-4"></i><?= esc($job['department']) ?></span><span class="flex items-center gap-1.5"><i data-lucide="map-pin" class="h-4 w-4"></i><?= esc($job['location'] ?: 'Location flexible') ?></span><span class="flex items-center gap-1.5"><i data-lucide="briefcase" class="h-4 w-4"></i><?= esc($job['work_mode'] ?: 'On-site') ?></span></div><p class="mt-5 line-clamp-2 text-sm leading-6 text-slate-600"><?= esc($job['description'] ?: 'Join our team and contribute to meaningful work in this role.') ?></p><a href="<?= base_url('careers/jobs/' . $job['id']) ?>" class="mt-6 inline-flex items-center gap-2 text-sm font-bold text-indigo-700">View role and apply <i data-lucide="arrow-right" class="h-4 w-4"></i></a></article><?php endforeach; ?>
<?php if (!$jobs): ?><div class="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center lg:col-span-2"><i data-lucide="search-x" class="mx-auto h-10 w-10 text-slate-400"></i><h3 class="mt-4 font-bold">No matching openings</h3><p class="mt-2 text-sm text-slate-500">Try removing one or more filters.</p></div><?php endif; ?>
</div></section></main><footer class="border-t bg-white px-5 py-6 text-center text-xs text-slate-500">© <?= date('Y') ?> GICHRMS · Equal opportunity careers portal</footer><script>lucide.createIcons()</script></body></html>
